services:
  ef:
    environment:
      SUPPRESS_ALERTS: false
      INTERDICTION_DESTINATION: global
      INTERDICTION_PRODUCER: interdiction-service-tp

  tp:
    environment:
      SUPPRESS_ALERTS: false
      INTERDICTION_DESTINATION: global
      INTERDICTION_PRODUCER: interdiction-service-tp

  tadp:
    environment:
      SUPPRESS_ALERTS: false
      ALERT_DESTINATION: global
      ALERT_PRODUCER: investigation-service
      ALERTS_ONLY: true

  ui:
    image: tazamaorg/demo-ui:rc
    restart: always
    env_file:
      - env/ui.env
    depends_on:
      - tms
      - postgres
      - nats
    ports:
      - "3001:3001"
  tms:
    environment:
      - CORS_POLICY=demo
  admin-service:
    environment:
      - CORS_POLICY=demo
