services:
  ef:
    environment:
      SUPPRESS_ALERTS: false
  tp:
    environment:
      SUPPRESS_ALERTS: false
  tadp:
    environment:
      SUPPRESS_ALERTS: false
  rs1:
    image: tazamaorg/relay-service-integration-nats:${TAZAMA_VERSION}
    env_file:
      - env/rs-nats-tp.env
      - .env
    restart: always
#    environment:
    depends_on:
      - tp

  rs2:
    image: tazamaorg/relay-service-integration-nats:${TAZAMA_VERSION}
    env_file:
      - env/rs-nats-tadp.env
      - .env
    restart: always
#    environment:
    depends_on:
      - tadp
