services:
  elasticsearch:
    image: elasticsearch:${STACK_VERSION}
    volumes:
      - esdata01:/usr/share/elasticsearch/data
    ports:
      - ${ES_PORT}:9200
    environment:
      - node.name=elasticsearch
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    mem_limit: ${ES_MEM_LIMIT}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl http://elasticsearch:9200",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  kibana:
    depends_on:
      elasticsearch:
        condition: service_healthy
    image: kibana:${STACK_VERSION}
    volumes:
      - kibanadata:/usr/share/kibana/data
    ports:
      - ${KIBANA_PORT}:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    mem_limit: ${KB_MEM_LIMIT}
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl http://localhost:5601",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  logstash:
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
    image: logstash:${STACK_VERSION}
    mem_limit: ${LS_MEM_LIMIT}
    volumes:
      - logstashdata:/usr/share/logstash/data
    environment:
      - xpack.monitoring.enabled=true
      - ELASTIC_HOSTS=http://elasticsearch:9200
      - ELASTIC_USER=elastic
      - ELASTIC_PASSWORD=""

  apm-server:
    image: elastic/apm-server:${STACK_VERSION}
    container_name: apm-server
    command: > # -e because logs
       apm-server -e
         -E apm-server.rum.enabled=true
         -E setup.kibana.host=http://kibana:5601
         -E setup.template.settings.index.number_of_replicas=0
         -E apm-server.kibana.enabled=true
         -E apm-server.kibana.host=http://kibana:5601
         -E output.elasticsearch.host=http://elasticsearch:9200
    ports:
      - ${APMSERVER_PORT}:8200
    depends_on:
      elasticsearch:
        condition: service_healthy

volumes:
 esdata01:
   driver: local
 kibanadata:
   driver: local
 logstashdata:
   driver: local