include:
  - path:
    - docker-compose.dev.elastic.yaml

services:
  tms:
    depends_on:
      - event-sidecar
    environment:
      SIDECAR_HOST: event-sidecar:${EVENT_SIDECAR_PORT}

  ed:
    depends_on:
      - event-sidecar
    environment:
      SIDECAR_HOST: event-sidecar:${EVENT_SIDECAR_PORT}

  rule-901:
    depends_on:
      - event-sidecar
    environment:
      SIDECAR_HOST: event-sidecar:${EVENT_SIDECAR_PORT}

  tp:
    depends_on:
      - event-sidecar
    environment:
      SIDECAR_HOST: event-sidecar:${EVENT_SIDECAR_PORT}

  tadp:
    depends_on:
      - event-sidecar
    environment:
      SIDECAR_HOST: event-sidecar:${EVENT_SIDECAR_PORT}

  event-sidecar:
    extends:
      file: docker-compose.dev.logs-base.yaml
      service: event-sidecar
  lumberjack:
    build:
      context: https://github.com/tazama-lf/lumberjack.git#${LUMBERJACK_BRANCH}
      args:
        - GH_TOKEN
    env_file:
      - env/lumberjack.env
      - .env
    restart: always
    depends_on:
      - event-sidecar
      - nats
    environment:
      ELASTIC_SEARCH_VERSION: ${ELASTIC_STACK_VERSION}
      ELASTIC_HOST: http://elasticsearch:9200
      ELASTIC: true
