services:
  ef:
    environment:
      SUPPRESS_ALERTS: false
  tp:
    environment:
      SUPPRESS_ALERTS: false
  tadp:
    environment:
      SUPPRESS_ALERTS: false
  rs1:
    image: !reset null
    build:
      context: https://github.com/tazama-lf/relay-service.git#${RELAY_BRANCH}
      args:
        - GH_TOKEN
    env_file:
      - env/rs-nats-tp.env
      - .env
    restart: always
#    environment:
    depends_on:
      - tp

  rs2:
    image: !reset null
    build:
      context: https://github.com/tazama-lf/relay-service.git#${RELAY_BRANCH}
      args:
        - GH_TOKEN
    env_file:
      - env/rs-nats-tadp.env
      - .env
    restart: always
#    environment:
    depends_on:
      - tadp
