# For local testing

services:
  redis:
    ports:
      - 16379:6379

  arango:
    environment:
      - ARANGO_NO_AUTH=1
    volumes:
      - ./arango/migration/local/01-SIMPLE.js:/docker-entrypoint-initdb.d/01-DATA.js
    ports:
      - 18529:8529

  nats:
    ports:
      - 14222:4222
      - 16222:6222
      - 18222:8222

  # RULE 901 (SAMPLE E2E RULE)
  rule-901:
    build:
      context: https://github.com/tazama-lf/rule-executer.git#${RULE_EXECUTER_BRANCH}
      args:
        - GH_TOKEN
    env_file:
      - env/rule-executer.env
      - .env
    restart: always
    depends_on:
      - redis
      - arango

