services:
  ef:
    environment:
      SUPPRESS_ALERTS: false
  tp:
    environment:
      SUPPRESS_ALERTS: false
  tadp:
    environment:
      SUPPRESS_ALERTS: false
  rs1:
    image: !reset null
    build:
      context: https://github.com/tazama-lf/relay-service.git#${RELAY_BRANCH}
      args:
        - GH_TOKEN
    env_file:
      - env/rs-nats.env
      - .env
    restart: always
    environment:
      FUNCTION_NAME: relay-service-tp
      CONSUMER_STREAM: interdiction-service
      PRODUCER_STREAM: relay-service-nats
    depends_on:
      - tp

  rs2:
    image: !reset null
    build:
      context: https://github.com/tazama-lf/relay-service.git#${RELAY_BRANCH}
      args:
        - GH_TOKEN
    env_file:
      - env/rs-rest.env
      - .env
    restart: always
    environment:
      FUNCTION_NAME: relay-service-tadp
      CONSUMER_STREAM: cms
      RETRY_ATTEMPTS: 10
      MAX_SOCKETS: 10
      AUTH_HEALTH_URL: http://keycloak:8080/health
      AUTH_TOKEN_URL: http://keycloak:8080
      DESTINATION_TRANSPORT_URL: ${MOCK_REST_URL}/create-new-case
      AUTH_USERNAME: tazama-user
      AUTH_PASSWORD: password
    depends_on:
      - tadp
