include:
  - path:
    - docker-compose.dev.elastic.yaml

services:
  event-sidecar:
    extends:
      file: docker-compose.dev.logs-base.yaml
      service: event-sidecar
  lumberjack:
    extends:
      file: docker-compose.dev.logs-base.yaml
      service: lumberjack
    environment:
      ELASTIC_SEARCH_VERSION: ${ELASTIC_STACK_VERSION}
      ELASTIC_HOST: http://elasticsearch:9200