services:
  postgres:
    volumes:
      - ./postgres/migration/config/00-public-base.sql:/docker-entrypoint-initdb.d/03-DATA.sql
      - ./postgres/migration/config/02-public-dockerhub.sql:/docker-entrypoint-initdb.d/04-DATA.sql

