services:
  # event-sidecar
  event-sidecar:
    image: tazamaorg/event-sidecar:${TAZAMA_VERSION}
    env_file:
      - .env
    ports:
      - 15000:${EVENT_SIDECAR_PORT}
    environment:
      NATS_SERVER: nats:4222
      NATS_SUBJECT: Lumberjack
      PORT: ${EVENT_SIDECAR_PORT}
    restart: always
    depends_on:
      - nats

  lumberjack:
    image: tazamaorg/lumberjack:${TAZAMA_VERSION}
    env_file:
      - env/lumberjack.env
      - .env
    environment:
      STDOUT: true
    restart: always
    depends_on:
      - event-sidecar
      - nats
