services:
  ef:
    environment:
      SUPPRESS_ALERTS: false
  tp:
    environment:
      SUPPRESS_ALERTS: false
  tadp:
    environment:
      SUPPRESS_ALERTS: false
  rs1:
    image: tazamaorg/relay-service:${TAZAMA_VERSION}
    env_file:
      - env/rs.env
      - .env
    environment:
      FUNCTION_NAME: tp-relay
      CONSUMER_STREAM: interdiction-service
    depends_on:
      - tp

  rs2:
    image: tazamaorg/relay-service:${TAZAMA_VERSION}
    env_file:
      - env/rs.env
      - .env
    environment:
      FUNCTION_NAME: tadp-relay
      CONSUMER_STREAM: cms
    depends_on:
      - tadp
