services:
  ef:
    environment:
      SUPPRESS_ALERTS: false
  tp:
    environment:
      SUPPRESS_ALERTS: false
  tadp:
    environment:
      SUPPRESS_ALERTS: false
  rs1:
    image: !reset null
    build:
      context: https://github.com/tazama-lf/relay-service.git#${RELAY_BRANCH}
      args:
        - GH_TOKEN
    env_file:
      - env/rs-nats.env
      - .env
    restart: always
    environment:
      FUNCTION_NAME: relay-service-tp
      CONSUMER_STREAM: interdiction-service
    depends_on:
      - tp

  rs2:
    image: !reset null
    build:
      context: https://github.com/tazama-lf/relay-service.git#${RELAY_BRANCH}
      args:
        - GH_TOKEN
    env_file:
      - env/rs-rest.env
      - .env
    restart: always
    environment:
      FUNCTION_NAME: relay-service-tadp
      CONSUMER_STREAM: cms
    depends_on:
      - tadp
