# For local testing

services:
  # AUTH SERVICE
  auth:
    build:
      context: https://github.com/tazama-lf/auth-service.git#${AUTH_SERVICE_BRANCH}
      args:
        - GH_TOKEN
    env_file:
      - env/auth-service.env
      - .env
    volumes:
      - ./auth/test-private-key.pem:/home/app/test-private-key.pem
    ports:
      - 3020:3020
    restart: always
    depends_on:
      - arango
      - keycloak
