[couchdb]
single_node=true
uuid = your-generated-uuid-here

[httpd]
enable_cors = true
max_http_request_size = 4294967296

[cors]
origins = *
credentials = true
methods = GET, PUT, POST, HEAD, DELETE
headers = accept, authorization, content-type, origin, referer, x-csrf-token

[log]
level = info

[chttpd]
bind_address = 0.0.0.0
port = 5984

[admins]
# Add your admin username and password here
# Format: username = -pbkdf2-84d514f5643b739cbe1759e8fbd519c05d4ebd41,350d34e683d12cc760e59f4a73ecb9a2,10
# CouchDB will automatically hash the password on first startup
tazama = -pbkdf2-7afe665139a08200b6ea3d430747920362a41b7f,02fd550fe740276a6870d5f6bac1ac1a,10
simon = -pbkdf2-1f5742898d5952bbe2a5f74eaaf5ae094f440bc4,a08153773c83d70a50224fc04a1bddda,10

[chttpd_auth]
# Generate a secure random secret string
secret = your-secret-key-here