services:
  event-monitoring-service:
    image: !reset null
    container_name: event-monitoring-service
    build:
      context: https://github.com/tazama-lf/event-monitoring-service.git#${DEMS_BRANCH}
      args:
        - GH_TOKEN
    env_file:
      - env/event-monitoring-service.env
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - ${DEMS_PORT}:3002

  data-enrichment-service:
    image: !reset null
    container_name: data-enrichment-service
    build:
      context: https://github.com/tazama-lf/data-enrichment-service.git#${DEAPI_BRANCH}
      args:
        - GH_TOKEN
    env_file:
      - env/data-enrichment-service.env
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - ${DEAPI_PORT}:3001


