services:
  connection-studio-backend:
    container_name: tcs-backend
    image: !reset null
    build:
      context: https://github.com/tazama-lf/connection-studio.git#${TCS_BRANCH}:backend
      args:
        - GH_TOKEN
    env_file:
      - env/tcs.env
      - .env
    restart: always
    ports:
      - ${TCS_PORT}:3010
    depends_on:
      - sftp
      - opensearch-node1
    volumes:
      - ./auth:/auth:ro

  connection-studio-frontend:
    container_name: tcs-frontend
    image: !reset null
    build:
      context: https://github.com/tazama-lf/connection-studio.git#${TCS_BRANCH}:frontend
      args:
        - GH_TOKEN
    env_file:
      - env/tcs.env
      - .env
    environment:
      - VITE_API_BASE_URL=http://${SERVER_B_HOST}:${TCS_PORT}
      - VITE_DATA_ENRICHMENT_SERVICE_URL=http://${SERVER_B_HOST}:${DEAPI_PORT}
      - VITE_ALLOWED_HOSTS=all
    restart: always
    ports:
      - ${TCS_FRONTEND_PORT}:5173
    depends_on:
      - sftp

  trs-backend:
    container_name: trs-backend
    image: !reset null
    build:
      context: https://github.com/tazama-lf/rule-studio.git#${TRS_BRANCH_BACKEND}:backend
      args:
        - GH_TOKEN
    env_file:
      - env/trs.env
      - .env
    restart: always
    depends_on:
      - opensearch-node1
    ports:
      - ${TRS_BACKEND_PORT}:3005
    volumes:
      - ./auth:/auth:ro

  trs-frontend:
    container_name: trs-frontend
    image: !reset null
    build:
      context: https://github.com/tazama-lf/rule-studio.git#${TRS_BRANCH_FRONTEND}:frontend
      args:
        - GH_TOKEN
    env_file:
      - env/trs.env
      - .env
    environment:
      - VITE_API_URL=http://${SERVER_B_HOST}:${TRS_BACKEND_PORT}
      - VITE_SANDBOX_API_URL=http://${SERVER_A_HOST}:3050
      - VITE_NATS_API_URL=http://${SERVER_A_HOST}:4000
      - VITE_SIMULATION_ENDPOINT=http://${SERVER_A_HOST}:5000/v1/evaluate/iso20022/pacs.002.001.12
      - VITE_DEMS_ENDPOINT=http://${SERVER_B_HOST}:${DEMS_PORT}
      - VITE_ADMIN_ENDPOINT=http://${SERVER_A_HOST}:3100
      - VITE_ALLOWED_HOSTS=all
    restart: always
    ports:
      - ${TRS_FRONTEND_PORT}:5174
    
  cms-backend:
    image: !reset null
    build:
      context: https://github.com/tazama-lf/case-management-system.git#${CMS_BRANCH}:backend
      args:
        - GH_TOKEN
      target: run-env
    container_name: tazama-cms-backend
    restart: unless-stopped
    depends_on:
      - migrate
      - flowable
      - opensearch-node1
    env_file:
      - ./env/cms.env
      - .env
    volumes:
      - ./auth/test-public-key.pem:/auth/test-public-key.pem:ro
    ports:
      - "${CMS_BACKEND_PORT}:3090"

  cms-frontend:
    image: !reset null
    build:
      context: https://github.com/tazama-lf/case-management-system.git#${CMS_BRANCH}:frontend
      args:
        - GH_TOKEN
    container_name: tazama-cms-frontend
    restart: unless-stopped
    env_file:
      - ./env/cms.env
      - .env
    environment:
      - VITE_API_BASE_URL=http://${SERVER_B_HOST}:${CMS_BACKEND_PORT}
      - VITE_ALLOWED_HOSTS=all
    ports:
      - "${CMS_FRONTEND_PORT}:5175"

  voila:
    image: !reset null
    build:
      context: https://github.com/tazama-lf/case-management-system.git#${CMS_BRANCH}
      dockerfile: Dockerfile.voila
      args:
        - GH_TOKEN
    container_name: tazama-cms-voila
    restart: unless-stopped
    env_file:
      - ./env/cms.env
      - .env
    environment:
      - CASE_MGMT_BACKEND_URL=http://tazama-cms-backend:3090
    ports:
      - "${VOILA_PORT:-18866}:8866"