services:
  core-pgadmin:
    container_name: core-pgadmin
    image: dpage/pgadmin4:9.15.0
    env_file:
      - env/core-pgadmin.env
    ports:
      - ${PGADMIN_PORT:-5050}:80
    environment:
      - GUNICORN_LIMIT_REQUEST_FIELDS=500
      - GUNICORN_LIMIT_REQUEST_FIELD_SIZE=16384
    configs:
      - source: servers.json
        target: /pgadmin4/servers.json
    restart: always
    depends_on:
      core-postgres:
        condition: service_healthy

configs:
  servers.json:
    content: |
      {
        "Servers": {
          "1": {
              "Name": "Tazama",
              "Group": "Servers",
              "Port": 5432,
              "Username": "postgres",
              "Host": "core-postgres",
              "MaintenanceDB": "postgres",
              "ConnectionParameters": {
                  "sslmode": "prefer",
                  "connect_timeout": 10
              }
          }
        }
      }