services:
  ef:
    environment:
      SUPPRESS_ALERTS: false
      INTERDICTION_DESTINATION: global
      INTERDICTION_PRODUCER: interdiction-service-ef

  tp:
    environment:
      SUPPRESS_ALERTS: false
      INTERDICTION_DESTINATION: global
      INTERDICTION_PRODUCER: interdiction-service-tp

  event-adjudicator:
    environment:
      SUPPRESS_ALERTS: false
      ALERTS_ONLY: false
      ALERT_DESTINATION: global
      ALERT_PRODUCER: investigation-service

  rsef:
    image: tazamaorg/relay-service-integration-nats:${TAZAMA_VERSION}
    env_file:
      - env/rs-nats.env
      - .env
    restart: always
    environment:
      FUNCTION_NAME: relay-service-ef
      CONSUMER_STREAM: interdiction-service-ef
      PRODUCER_STREAM: relay-service-nats-ef
      APM_SERVICE_NAME: relay-service-ef
    depends_on:
      - ef

  rstp:
    image: tazamaorg/relay-service-integration-nats:${TAZAMA_VERSION}
    env_file:
      - env/rs-nats.env
      - .env
    restart: always
    environment:
      FUNCTION_NAME: relay-service-tp
      CONSUMER_STREAM: interdiction-service-tp
      PRODUCER_STREAM: relay-service-nats-tp
      APM_SERVICE_NAME: relay-service-tp
    depends_on:
      - tp

  rsea:
    image: tazamaorg/relay-service-integration-nats:${TAZAMA_VERSION}
    env_file:
      - env/rs-nats.env
      - .env
    restart: always
    environment:
      FUNCTION_NAME: relay-service-ea
      CONSUMER_STREAM: investigation-service
      PRODUCER_STREAM: relay-service-nats-ea
      APM_SERVICE_NAME: relay-service-ea
    depends_on:
      - event-adjudicator