services:
  batch-ppa:
    image: tazamaorg/batch-ppa:${TAZAMA_VERSION}
    env_file:
      - env/batch-ppa.env
      - .env
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
      tms:
        condition: service_started
    ports:
      - 4000:4000