# base infrastructure

services:
  valkey:
    container_name: valkey
    hostname: valkey
    image: valkey/valkey:7.2.5
    restart: always
    command: "valkey-server --port 6379 --loglevel verbose"
    healthcheck:
      test: ["CMD-SHELL", "valkey-cli -p 6379 ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5

  core-postgres:
    container_name: core-postgres
    image: postgres:18
    restart: always
    volumes:
      - ./postgres/migration/base:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 120s
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=unused

  nats:
    container_name: nats
    image: nats:2
    restart: always
    command: ["-DVV"]
